name: Publish Python Package to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine markdown  # <-- Added 'markdown' dependency
    
    - name: Build package
      run: |
        python -m build
    
    - name: Check built distributions
      run: |
        ls -la dist/
        echo "Built packages:"
        find dist/ -type f -name "*.tar.gz" -o -name "*.whl"
    
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m twine upload dist/*

  test-package:
    runs-on: ubuntu-latest
    needs: build-and-publish
    
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    
    - name: Install from PyPI
      run: |
        python -m pip install --upgrade pip
        # Tunggu beberapa detik untuk package tersedia
        sleep 30
        pip install newscrap
    
    - name: Test installation
      run: |
        python -c "import news_scrap; print('Module imported successfully')"
        python -m news_scrap --help

  quality-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
    
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
